authors = ["Marius Furter"]
name = "DrawingInferences"
uuid = "8bbfcb55-b00a-4584-9d90-4bfd50a3e99a"
version = "1.0.1-DEV"

[deps]
Gen = "ea4f424c-a589-11e8-07c0-fd5c91b9da4a"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
