name = "DrawingInferences"
uuid = "8bbfcb55-b00a-4584-9d90-4bfd50a3e99a"
authors = ["Marius Furter"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
