name = "DrawingInferences"
uuid = "e5b4febb-f41c-4386-84f4-e73e26fd4cda"
authors = ["Marius Furter"]
version = "1.0.0-DEV"

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"

[compat]
MacroTools = "0.5.16"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
